# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "862a68630446c3aa82aa67d485ad9077"
name = "Yespo: Email marketing, pop-up"
handle = "yespo-app"
application_url = "https://yespo-app-e02c70c13f7d.herokuapp.com/"
embedded = true

[build]
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_markets,read_themes,write_app_proxy"

[auth]
redirect_urls = [
  "https://yespo-app-e02c70c13f7d.herokuapp.com/auth/callback",
  "https://yespo-app-e02c70c13f7d.herokuapp.com/auth/shopify/callback",
  "https://yespo-app-e02c70c13f7d.herokuapp.com/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  uri = "https://yespo-app-e02c70c13f7d.herokuapp.com/webhooks/app/gdpr"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "customers/create", "customers/update" ]
  uri = "https://yespo-app-e02c70c13f7d.herokuapp.com/webhooks/app/customers"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://yespo-app-e02c70c13f7d.herokuapp.com/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://yespo-app-e02c70c13f7d.herokuapp.com/webhooks/app/uninstalled"

[app_proxy]
url = "https://push.yespo.io/"
subpath = "yespo-proxy"
prefix = "apps"

[pos]
embedded = false
