# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "12e4a9a47ee6beaf4ee3f4775eb80fba"
application_url = "https://battle-imagine-normally-hostels.trycloudflare.com"
embedded = true
name = "yespo-app"
handle = "yespo-app"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  uri = "https://lately-exotic-bluebird.ngrok-free.app/webhooks/app/gdpr"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://lately-exotic-bluebird.ngrok-free.app/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://lately-exotic-bluebird.ngrok-free.app/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_markets,read_themes"

[auth]
redirect_urls = [
  "https://battle-imagine-normally-hostels.trycloudflare.com/auth/callback",
  "https://battle-imagine-normally-hostels.trycloudflare.com/auth/shopify/callback",
  "https://battle-imagine-normally-hostels.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://battle-imagine-normally-hostels.trycloudflare.com"
subpath = "yespo-proxy"
prefix = "apps"

[pos]
embedded = false
