# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "12e4a9a47ee6beaf4ee3f4775eb80fba"
application_url = "https://magnet-experience-fall-marshall.trycloudflare.com"
embedded = true
name = "yespo-app"
handle = "yespo-app"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://magnet-experience-fall-marshall.trycloudflare.com/auth/callback",
  "https://magnet-experience-fall-marshall.trycloudflare.com/auth/shopify/callback",
  "https://magnet-experience-fall-marshall.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
