export const EVENT_MESSAGES = {
  ADD_API_KEY_SUCCESS: "ADD_API_KEY_SUCCESS",
  ADD_API_KEY_FAILED: "ADD_API_KEY_FAILED",
  ADD_DOMAIN_SUCCESS: "ADD_DOMAIN_SUCCESS",
  ADD_DOMAIN_FAILED: "ADD_DOMAIN_FAILED",
  INSERT_SITE_SCRIPT_SUCCESS: "INSERT_SITE_SCRIPT_SUCCESS",
  INSERT_SITE_SCRIPT_FAILED: "INSERT_SITE_SCRIPT_FAILED",
  GET_SCRIPT_SUCCESS: "GET_SCRIPT_SUCCESS",
  GET_SCRIPT_FAILED: "GET_SCRIPT_FAILED",
  ADD_WEB_PUSH_DOMAIN_SUCCESS: "ADD_WEB_PUSH_DOMAIN_SUCCESS",
  ADD_WEB_PUSH_DOMAIN_FAILED: "ADD_WEB_PUSH_DOMAIN_FAILED",
  GET_WEB_PUSH_DOMAIN_SUCCESS: "GET_WEB_PUSH_DOMAIN_SUCCESS",
  GET_WEB_PUSH_DOMAIN_FAILED: "GET_WEB_PUSH_DOMAIN_FAILED",
  INSERT_WEB_PUSH_SCRIPT_SUCCESS: "INSERT_WEB_PUSH_SCRIPT_SUCCESS",
  INSERT_WEB_PUSH_SCRIPT_FAILED: "INSERT_WEB_PUSH_SCRIPT_FAILED",
  ADD_SERVICE_WORKER_SUCCESS: "ADD_SERVICE_WORKER_SUCCESS",
  ADD_SERVICE_WORKER_FAILED: "ADD_SERVICE_WORKER_FAILED",
  DATA_SYNC_ENABLED: "DATA_SYNC_ENABLED",
  DATA_SYNC_DISABLED: "DATA_SYNC_DISABLED",
  DATA_SYNC_FAILED: "DATA_SYNC_FAILED",
  SEND_CONTACTS_BULK_SUCCESS: "SEND_CONTACTS_BULK_SUCCESS",
  SEND_CONTACTS_BULK_FAILED: "SEND_CONTACTS_BULK_FAILED",
  SEND_ORDERS_BULK_SUCCESS: "SEND_ORDERS_BULK_SUCCESS",
  SEND_ORDERS_BULK_FAILED: "SEND_ORDERS_BULK_FAILED",
  SEND_PRODUCT_VARIANTS_BULK_SUCCESS: "SEND_PRODUCT_VARIANTS_BULK_SUCCESS",
  SEND_PRODUCT_VARIANTS_BULK_FAILED: "SEND_PRODUCT_VARIANTS_BULK_FAILED",
  WEB_TRACKING_ENABLED: "WEB_TRACKING_ENABLED",
  WEB_TRACKING_DISABLED: "WEB_TRACKING_DISABLED",
  WEB_TRACKING_FAILED: "WEB_TRACKING_FAILED",
  WEB_TRACKING_STATUSCART_SUCCESS: "WEB_TRACKING_STATUSCART_SUCCESS",
  WEB_TRACKING_STATUSCART_ERROR: "WEB_TRACKING_STATUSCART_ERROR",
  WEB_TRACKING_PURCHASED_ITEMS_SUCCESS: "WEB_TRACKING_PURCHASED_ITEMS_SUCCESS",
  WEB_TRACKING_PURCHASED_ITEMS_ERROR: "WEB_TRACKING_PURCHASED_ITEMS_ERROR",
  WEB_TRACKING_CUSTOMER_DATA_SUCCESS: "WEB_TRACKING_CUSTOMER_DATA_SUCCESS",
  WEB_TRACKING_CUSTOMER_DATA_ERROR: "WEB_TRACKING_CUSTOMER_DATA_ERROR",
  // custom logs
  CUSTOM_LOG_SEND_ACCESS_TOKEN_ERROR: "CUSTOM_LOG_SEND_ACCESS_TOKEN_ERROR",
  CUSTOM_LOG_DELETE_ACCESS_TOKEN_ERROR: "CUSTOM_LOG_DELETE_ACCESS_TOKEN_ERROR",
  CUSTOM_LOG_DISCONNECT_ACCOUNT_ERROR: "CUSTOM_LOG_DISCONNECT_ACCOUNT_ERROR",
  CUSTOM_LOG_GET_ACCOUNT_INFO_ERROR: "CUSTOM_LOG_GET_ACCOUNT_INFO_ERROR",
  CUSTOM_LOG_GET_STORE_THEME_ERROR: "CUSTOM_LOG_GET_STORE_THEME_ERROR",
  CUSTOM_LOG_CHECK_THEME_EXTENSION_ERROR:
    "CUSTOM_LOG_CHECK_THEME_EXTENSION_ERROR",
  CUSTOM_LOG_CREATE_YESPO_ORDERS_SUCCESS:
    "CUSTOM_LOG_CREATE_YESPO_ORDERS_SUCCESS",
  CUSTOM_LOG_CREATE_YESPO_ORDERS_ERROR: "CUSTOM_LOG_CREATE_YESPO_ORDERS_ERROR",
  CUSTOM_LOG_DELETE_YESPO_CONTACTS_ERROR:
    "CUSTOM_LOG_DELETE_YESPO_CONTACTS_ERROR",
  CUSTOM_LOG_CHECK_SHOPIFY_MARKETS_ERROR:
    "CUSTOM_LOG_CHECK_SHOPIFY_MARKETS_ERROR",
  CUSTOM_LOG_APP_INBOX_MODE_ENABLED_ERROR:
    "CUSTOM_LOG_APP_INBOX_MODE_ENABLED_ERROR",
  CUSTOM_LOG_APP_INBOX_MODE_DISABLED_ERROR:
    "CUSTOM_LOG_APP_INBOX_MODE_DISABLED_ERROR",
  CUSTOM_LOG_SEND_PRODUCT_VARIANTS_SUCCESS:
    "CUSTOM_LOG_SEND_PRODUCT_VARIANTS_SUCCESS",
  CUSTOM_LOG_SEND_PRODUCT_VARIANTS_ERROR:
    "CUSTOM_LOG_SEND_PRODUCT_VARIANTS_ERROR",
  CUSTOM_LOG_SEND_MARKET_PRODUCTS_SUCCESS:
    "CUSTOM_LOG_SEND_MARKET_PRODUCTS_SUCCESS",
  CUSTOM_LOG_SEND_MARKET_PRODUCTS_ERROR:
    "CUSTOM_LOG_SEND_MARKET_PRODUCTS_ERROR",
  CUSTOM_LOG_MARKET_SYNC_CLEANUP_SUCCESS:
    "CUSTOM_LOG_MARKET_SYNC_CLEANUP_SUCCESS",
  CUSTOM_LOG_MARKET_SYNC_CLEANUP_ERROR:
    "CUSTOM_LOG_MARKET_SYNC_CLEANUP_ERROR",
  CUSTOM_LOG_DELETE_PRODUCT_VARIANTS_SUCCESS:
    "CUSTOM_LOG_DELETE_PRODUCT_VARIANTS_SUCCESS",
  CUSTOM_LOG_DELETE_PRODUCT_VARIANTS_ERROR:
    "CUSTOM_LOG_DELETE_PRODUCT_VARIANTS_ERROR",
  CUSTOM_LOG_BULK_OPERATION_ERROR: "CUSTOM_LOG_BULK_OPERATION_ERROR",

  CREATE_CONTACT_SUCCESS: "CREATE_CONTACT_SUCCESS",
  CREATE_CONTACT_FAILED: "CREATE_CONTACT_FAILED",
  UPDATE_CONTACT_SUCCESS: "UPDATE_CONTACT_SUCCESS",
  UPDATE_CONTACT_FAILED: "UPDATE_CONTACT_FAILED",

  CUSTOM_LOG_UPDATE_YESPO_CONTACTS_SUCCESS:
    "CUSTOM_LOG_UPDATE_YESPO_CONTACTS_SUCCESS",
  CUSTOM_LOG_UPDATE_YESPO_CONTACTS_ERROR:
    "CUSTOM_LOG_UPDATE_YESPO_CONTACTS_ERROR",
} as const;

export type EventMessage = (typeof EVENT_MESSAGES)[keyof typeof EVENT_MESSAGES];

export const LOG_ORG_ID = 23948;

/**
 * Maximum number of shops the market-sync cron keeps in progress at once.
 * Each cron tick only enqueues up to `MARKET_SYNC_MAX_CONCURRENT_SHOPS` minus
 * the shops already syncing.
 */
export const MARKET_SYNC_MAX_CONCURRENT_SHOPS = 10;

/**
 * A shop's market sync is treated as "in progress" only while its newest
 * IN_PROGRESS MarketSyncLog is fresher than this. Older IN_PROGRESS rows are
 * considered stuck (e.g. a crashed/restarted worker), no longer count against
 * the concurrency budget, and let the shop be picked up again.
 */
export const MARKET_SYNC_STALE_AFTER_MS = 5 * 60 * 60 * 1000;

/**
 * Minimum time between automatic (cron) market syncs for a shop. The cron skips
 * a shop whose last successful (COMPLETE) sync finished less than this ago, so a
 * single shop is not re-synced every hour. Never-synced shops and shops whose
 * last sync ended in ERROR are not throttled. Manual/dashboard and post
 * data-sync triggers bypass this interval entirely.
 */
export const MARKET_SYNC_MIN_INTERVAL_MS = 24 * 60 * 60 * 1000;

/**
 * How many times `fetchWithErrorHandling` retries a request after the server
 * responds with HTTP 429 (Rate Limited) before giving up and throwing.
 */
export const RATE_LIMIT_MAX_RETRIES = 3;

/**
 * Fallback wait time before retrying a 429 response when the server does not
 * send a usable `Retry-After` header. Yespo limits to 60 req/min per siteId, so
 * a full minute is the safe default.
 */
export const RATE_LIMIT_DEFAULT_RETRY_AFTER_MS = 60 * 1000;
